SUSE/hackweek

Gemfile
Gemfile.lock
app/models/comment.rb
app/models/project.rb
bin/rails
bin/rake
bin/spring
spec/factories/comments.rb
spec/factories/projects.rb
spec/models/comment_spec.rb
spec/models/project_spec.rb
spec/rails_helper.rb

Closes #104 
Also introduces some fancy development tools.

dependent: :destroy on comments

---

app/controllers/projects_controller.rb
app/models/episode.rb
app/models/episode_project_association.rb
app/models/project.rb
app/views/projects/_tabs.html.haml
app/views/projects/newest.rss.haml
db/migrate/20150319172246_model_for_episodes_projects_association.rb
db/schema.rb
spec/controllers/projects_controller_spec.rb
spec/factories/episode_project_associations.rb
spec/factories/projects.rb
spec/models/episode_project_association_spec.rb

Rss feed of projects

---

.gitignore
Gemfile
Gemfile.lock
README.md
Vagrantfile
bootstrap.sh
config/boot.rb
config/database.yml

To enable our a little bit more complex setup (real SQL server + searchd) we need a turn-key solution for development and testing environments. (Or else we'll be forced to answer numerous questions on how to install Sphinx search in MacOS and so on.)
Vagrant seems to be an ideal tool for our cause. I've tried to make the setup as automated as possible; There is also a new section in the Readme with full step-by-step guid on how to get started (should be platform-independent).

Vagrantified development

---

bootstrap.sh

Gemfile requires sqlite3, but sqlite3-devel is missing the box. This
causes bundle exec to fail.

Add missing sqlite3-devel to bootstrap

---

Vagrantfile
config/initializers/better_errors.rb

We've been running better_errors inside a Vagrant box — and were forbidden by the default security scope from actually using the gem.
This PR fixes that, but still might require some tweaks for every user — as IP adresses Vagrant uses might change from machine to machine.

Fix better errors

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/hackweek.css.scss
app/controllers/markdown_controller.rb
app/helpers/markdown_helper.rb
app/views/layouts/application.html.haml
app/views/markdown/preview.js.erb
app/views/projects/_form.html.haml
bootstrap.sh
config/routes.rb
spec/controllers/markdown_controller_spec.rb
spec/features/project_management_spec.rb
spec/helpers/markdown_helper_spec.rb
spec/rails_helper.rb
spec/views/markdown/preview.js.erb_spec.rb

Closes #91
Opens previews in a modal popup window.
Works via javascript and AJAX.
Should be more or less covered by tests (and that coverage is easy to extend in case of bugs).
Currently only bound to Project description form field, but should be pretty easy to attach to other forms/fields as well.

Markdown preview

---

app/controllers/application_controller.rb
app/views/layouts/_header.html.haml
app/views/projects/newest.rss.haml
spec/controllers/projects_controller_spec.rb

Closes #126
But I really don't like duplication between `ApplicationController#set_episode` and `ProjectsController#load_episode`

Fixed RSS error for :all episodes

---

Gemfile
Gemfile.lock

Add rack-mini-profiler gem (enabled in development mode only by default), so we can spot performance bottlenecks in rendering/sql queries.

Add rack-mini-profiler

---

app/controllers/projects_controller.rb

This removes the N+1 query pattern on the project pages. This change brings down the page load time from ~1800ms to ~ 1630ms, measured on a warmed up projects index page in development mode, with database on the same host.

Eager load associations for project lists on frontpage

---

Gemfile
Gemfile.lock
app/decorators/project_decorator.rb
app/views/projects/_list.html.haml
app/views/projects/_list_item.html.haml
app/views/projects/index.html.haml
app/views/search/result.html.haml

Rendering many / nested HAML partials is taking ~ 40-60ms per project/list_item partial in development mode on a warmed up page, using last weeks production data. This can be a problem when there are many projects displayed on a page.
This patch introduces the draper gem, which provides a framework for 'decorators' - a glue code between views and models, somewhat similar to helpers.
It then duplicates some partials code into the projects_decorator methods.
Finally, it replaces partial rendering in the 'projects/list_item' with these methods and fixes the partial's callees to decorate project objects.
The list_item partial now renders in around 15ms, bringing down the page load time to ~45% (from 1800ms to 950ms for index page with 100 projects) in development mode. Combined with #133, the …

Replace partials with decorator methods on project page

---

config/initializers/hoptoad.rb

Do not report ActiveRecord::RecordNotFound to hoptoad, so that the
hackweek mailing list does not get spammed by exception reports caused
by users mistyping URLs.

Ignore NotFound error in hoptoad

---

app/views/users/show.html.haml

That tab should be what the user is currently working on and then the number is different and is confusing for the user.
I also removed some unused branch/conditions. :bowtie: 
Solves #186.

 Check in Works on tab what is rendered && refactoring

---

app/views/layouts/application.html.haml

This cause timeout and we don't need it for test and travis.

Disable piwik for test and travis

---

app/views/markdown/preview.js.erb

Fix authenticity_token bug

---

app/controllers/projects_controller.rb
app/models/project.rb
spec/controllers/projects_controller_spec.rb

Previously we did not check whether a user already joined a project
before adding him. So it was possible to join a project multiple times.
Fixes #94

Prevent users from joining a project twice

---

app/controllers/projects_controller.rb
app/models/project.rb
spec/features/collaboration_spec.rb

User(originator) wasnt able to become project's kudos element because of table join error.
Closes #193 
There was an error in left outer join during includes(args), by which originator wasn't included in his project's kudos.
So, he can like his project multiple times upon refresh

Resolve User(originator) kudos bug

---

app/assets/javascripts/application.js
app/assets/stylesheets/hackweek.scss
app/controllers/comments_controller.rb
app/views/comments/_comment.html.haml
app/views/comments/_form.html.haml
app/views/comments/_reply_modal.html.haml
app/views/comments/reply_modal.js.erb
app/views/markdown/preview.js.erb
app/views/projects/_form.html.haml
app/views/projects/show.html.haml
app/views/shared/_editor_buttons.html.haml
config/routes.rb
spec/features/project_management_spec.rb

Now, for replying to a comment,
- Instead of directing the user to a different page(comment#new), a reply modal is opened for the user to write the reply on the same page(project#show).
Inspired from _Twitter_

Change user flow for replying to a comment

---

.travis.yml

Because in docker we are using ruby 2.5.0

Use ruby 2.5.0 in Travis

---

config/deploy.rb

Using `https` as the prefix of the repository url throw an `error:1407742E:SSL` error. Switching to `git` fixed it.
Co-authored-by: Henne Vogelsang <hvogel@opensuse.org>

Fix repository url to deploy with mina

---

app/assets/javascripts/application.js

Every comment field has a couple of style options, like adding emojis
and links.
The events that get triggered by pressing these buttons are attached
to the comment's textfield and break when the field is gone, eg. when
in preview mode.
Hiding these buttons in preview mode solves the problem. Also these
buttons are not useful for the preview anyway.

Hide comment style bar in preview mode

---

Gemfile
Gemfile.lock
config/environments/production.rb

We now use the gem lograge to show one line per request instead of
multiple lines
Co-authored-by: David Kang <dkang@suse.com>
Co-authored-by: Moises Deniz Aleman <mdeniz@suse.com>

Change the way we do logging in production

---

app/controllers/users_controller.rb
app/views/users/edit.html.haml
spec/controllers/users_controller_spec.rb

We are behind a login proxy, user management is not happening
in our app.
Fixes #291

Remove User.name/email updating

---

config/environments/production.rb

- Our current user is called different
- We don't need to log the remote address

Fix up lograge config

---

app/controllers/projects_controller.rb
app/helpers/application_helper.rb
app/models/project.rb
app/views/announcements/_announcement_toggle.js.erb
app/views/layouts/application.html.haml
app/views/projects/_hackers.html.haml
app/views/projects/_membership_buttons.html.haml
app/views/projects/join.js.erb
app/views/projects/leave.js.erb
app/views/projects/show.html.haml
config/routes.rb
spec/controllers/projects_controller_spec.rb
spec/features/collaboration_spec.rb
spec/models/project_spec.rb

Fixes two sources of  `InvalidAuthenticityToken` exceptions:
1. People clicking repeatedly on `join`/`leave` 
2. People enrolling in an announcement while doing other things
This should somewhat help a bit...

Fixes two sources of InvalidAuthenticityToken exceptions

---

db/schema.rb

Remove impressions table from schema.rb
In my #296 ,Due to bad rebasing of commit I added impressions table to schema (without any migrations) from my #224 pr.

Correct schema.rb

---

config/routes.rb

We only have new and create as resourceful routes for
comments.

Limit comments routes to what the controller supports

---

app/views/about/index.html.haml

Episode.description is blank by default, but always exists so
the default description was never rendered.

Fix description rendering

---

app/models/user.rb

The relationship of comments of a user was using 'user_id' instead of 'commenter_id'.
Co-authored-by: David Kang <dkang@suse.com>
Fixes #438

Add missing foreign_key in users model

---

app/models/keyword.rb
app/views/keywords/_new.html.haml

Making it required we improve a little bit the user experience and
also we avoid sending failed requests due to an empty keyword param.

Make keyword input required

---

app/views/about/index.html.haml

When we start the app from scrach we don't have episode and we can't
get the description from the episode.

Avoid to crash when we don't have episode

---

app/assets/javascripts/application.js
app/controllers/comments_controller.rb
app/controllers/markdown_controller.rb
app/helpers/application_helper.rb

The url for github emoji has changed from `https://assets-cdn.github.com`
`to https://github.githubassets.com`

Change github emoji cdn

---

app/controllers/search_controller.rb
app/indices/project_index.rb
app/indices/user_index.rb

After migrating to sphinx real-time indices, the episodes should have been indexed as a multi-value attribute.
Also, after starting to use real-time indices there is no need to also use active record indices.

Fix search by episode

---

docker-compose.yml

Switch base system from Leap 42.3 to Leap 15.1.
This way, the base system used in the mariadb container is the same one used in the hackweek container.

Update mariadb docker container

---

Dockerfile

Prevent this warning to happen:
`'libmysqld-devel' not found in package names. Trying capabilities.`
This made packages `libmariadb-devel` and `libmariadbd-devel` to be installed. The last one turns out not to be necessary.
The development files for MariaDB contained in the `libmariadb-devel` package, are only used to install the `mysql2` gem.

Update package with development files for MariaDB

---

app/controllers/search_controller.rb

Prevent crashing in search terms including `/`.
Fixes #707.

Escape query parameter in searches

---

app/helpers/markdown_helper.rb
app/views/projects/_list_item.html.haml

Don't cut markdown preview after 140 chars, which can lead to invalid syntax. Cut after n lines instead and filter out comments and empty lines.

Don't cut markdown preview after 140 chars

---

config/deploy.rb

pumactl restart does not make the worker re-read their
working directory. Hence new code is never used...
Use stop/start via systemd again.

Fix restart during deploy

---

app/views/layouts/_notification_tab.html.haml

According to https://fontawesome.com/v4/icon/bell
this is the right way to refer to it, and now it shows up again.

recover bell icon

---

app/views/users/show.html.haml

if there is no user logged in, do not show the email address of other users even if the hide_email flag is not set. This avoids scrapers and search engines picking it up.

Hide e-mail addresses from anonymous views

---

app/assets/stylesheets/hackweek.scss

Images embedded in the project body, which are wider than the body itself, will overflow into the side panel. This simple fix limits the max width of images to 100% of the parent container.

Fix image overflow in project body

---

config/deploy.rb

Push public/img to shared_dirs

---

app/assets/stylesheets/hackweek.scss

This fixes ugly (non-existing) image spacing in dropdown notifications when the project has a logo.
Before:
After:

Add margin to image in dropdown notifications

---

Gemfile
Gemfile.lock

- Only directly require what we really require
- Bundle with the bundler version our openSUSE ruby package ships
- Stop mixing group block and group opt feature

Cleanup Gemfile
