SUSE/hackweek

app/views/comments/_form.html.haml
app/views/comments/new.html.haml
app/views/projects/show.html.haml
spec/features/project_management_spec.rb

Finally closes #91 completely (and removes some duplication in comments views).

Markdown preview for comments

---

app/assets/stylesheets/hackweek.css.scss
app/views/comments/_form.html.haml
app/views/layouts/_footer.html.haml
app/views/layouts/_header.html.haml
app/views/projects/_list_item.html.haml
app/views/projects/index.html.haml
app/views/projects/show.html.haml

- Added some new classes in HAML files and in css file.
- Improved the appearance of the hackweek project page (right side panel). 
- Apply css to all Header (H1, H2..), p and ul/ui tag.
- Improved the appearance of right side panel.
- Moved News, About, pics and credit links from footer to header section.

Worked on css

---

app/indices/project_index.rb
app/models/comment.rb
app/models/project.rb

Add comment contents to the search index

---

app/views/about/index.html.haml

I decided to not upload it to Youtube as its content is more
inbound oriented.
Please push it online before tomorrow, thanks!

Added welcome to Hackweek 0x10 video by Ralf Flaxa.

---

app/views/about/index.html.haml

People reported problems when trying to play the video, this
additional encoded version should help. At least it does not
make it worse...

Add a webm encoded video of Ralfs hackweek video as alternative.

---

app/views/about/index.html.haml

Fix a typo that was added with my previous commit.

Fix typo, type is webm, not wem

---

public/404.html
public/422.html
public/500.html
public/assets/stylesheets/common.css

Error pages : 404.html,500.html & 422.html modified with also keeping app's pages UI into consideration as well.
Closes #189
**500 :**
**400 :**
**422 :**

Update error pages

---

Gemfile
Gemfile.lock

To fix https://nvd.nist.gov/vuln/detail/CVE-2017-0889

update paperclip gem

---

.rubocop_todo.yml
app/models/ability.rb
spec/spec_helper.rb

Comments made well indented
Closes #207

Fix rubocop's Layout/CommentIndentation

---

.rubocop_todo.yml
spec/controllers/markdown_controller_spec.rb
spec/controllers/projects_controller_spec.rb
spec/factories/comments.rb
spec/factories/episode_project_associations.rb
spec/features/project_management_spec.rb

Fix rubocop's Layout/EmptyLinesAroundBlockBody.

---

app/views/projects/_like_toggle.js.erb

Fixes #213
Fixed invalid authenticity_token error which occurred due to like/dislike action through ajax. So here csrf_token is replace with new token to submit request without any error and authenticity_token is change for comment form

Fixed invalid authenticity_token error

---

app/assets/javascripts/application.js
app/assets/stylesheets/hackweek.scss
app/controllers/markdown_controller.rb
app/controllers/projects_controller.rb
app/views/comments/_form.html.haml
app/views/layouts/application.html.haml
app/views/projects/_form.html.haml
app/views/projects/show.html.haml
app/views/shared/_editor_buttons.html.haml
spec/features/project_management_spec.rb

- Added text formatting buttons for comments/project forms for better ux.
- User mentioning dropdown added on typing '@' keyword, similar to emoticons on ':' symbol.

Improved Comment/Project forms

---

app/controllers/application_controller.rb
spec/controllers/projects_controller_spec.rb

* Fixes 404 page for not found projects and other resources.
* Includes some minor refactoring of the project controller tests

Render 404 page in case of uncatched RecordNotFound exception

---

app/assets/stylesheets/hackweek.scss
app/controllers/projects_controller.rb
app/models/project.rb
app/views/projects/_similar_projects.html.haml
app/views/projects/show.html.haml
spec/features/project_management_spec.rb
spec/models/project_spec.rb

Unique similar projects as per the keyword added in project#show

Add Similar Project

---

app/assets/stylesheets/hackweek.scss
app/controllers/projects/project_follows_controller.rb
app/controllers/projects_controller.rb
app/models/project.rb
app/models/project_follow.rb
app/models/user.rb
app/views/projects/_project_watch.html.haml
app/views/projects/show.html.haml
config/routes.rb
db/migrate/20180619192048_create_project_follows.rb
db/schema.rb
spec/controllers/projects/project_follows_controller_spec.rb

**In this PR :** 
- Add addition relationship between user and project model , i.e. project_follow.rb .
- Add watch-unwatch buttons in view & follow-unfollow methods in project controller .
- Add modal for showing project's watchers .
---
---

Add watch~unwatch feature to project

---

Gemfile
Gemfile.lock
config/deploy.rb
config/puma.rb

For the deployment on a SLE15 host we use puma and a package to ship the configuration so we need some changes to the deploy script

SLE15 deployment

---

app/controllers/application_controller.rb
app/controllers/search_controller.rb
app/indices/project_index.rb
app/views/layouts/_header.html.haml
config/routes.rb

Co-authored-by: Kaustubh Nair <kaustubh.nair108@gmail.com>

Filter search by episode

---

app/controllers/projects_controller.rb
app/models/project.rb
app/views/projects/_similar_projects.html.haml
app/views/projects/show.html.haml
spec/models/project_spec.rb

Add accordian for similar project in projects#show
Closes #289

Add Accordian for similar projects

---

app/assets/javascripts/application.js
app/assets/stylesheets/hackweek.scss
app/controllers/announcements_controller.rb
app/controllers/application_controller.rb
app/controllers/comments_controller.rb
app/controllers/notifications_controller.rb
app/controllers/projects_controller.rb
app/models/comment.rb
app/models/notification.rb
app/models/project.rb
app/models/user.rb
app/views/layouts/_header.html.haml
app/views/layouts/_notification_tab.html.haml
app/views/notifications/index.html.haml
app/views/notifications/mark_as_read.js.erb
config/routes.rb
db/migrate/20180702104632_create_notifications.rb
db/migrate/20180712105306_add_description_to_episodes.rb
db/schema.rb
spec/controllers/markdown_controller_spec.rb
spec/controllers/notifications_controller_spec.rb
spec/controllers/projects_controller_spec.rb
spec/factories/notifications.rb
spec/models/project_spec.rb

- From now on, whenever a user creates a project/joins a project he will be automatically be added as member of project_followers(watcher).
- Notifications will be created whenever a person joins/likes or create a comment on a project.
older notifications page:

Navbar Notifications

---

Gemfile
Gemfile.lock
app/controllers/projects_controller.rb
app/models/project.rb
config/initializers/impression.rb
db/migrate/20180730125036_create_impressions_table.rb
db/migrate/20180730151836_add_projecthits_to_projects.rb
db/schema.rb
spec/controllers/projects_controller_spec.rb

- Added Impressionist gem for adding visibility parameter for projects
- Add column projecthits(ie: kudos+views), as a new parameter for rendering projects list for better visibility
- ALL projects order : projecthits ASC
- Popular projects order : projecthits DESC

Improvement of Projects Visibility

---

app/models/user.rb

Somehow the hash had different access

Fixes user creation

---

app/controllers/faqs_controller.rb
app/models/ability.rb
app/models/faq.rb
app/views/faqs/_form.html.haml
app/views/faqs/edit.html.haml
app/views/faqs/index.html.haml
app/views/faqs/new.html.haml
app/views/layouts/_footer.html.haml
config/routes.rb
db/migrate/20180820211721_create_faqs.rb
db/schema.rb

Introduces a simple FAQ

---

app/models/announcement.rb

Define association before using it in :through

---

config/deploy.rb
config/thinking_sphinx.yml.example

Move deployment into /home/hwrun

---

README.md

This makes the README look nicer.

Reformat ordered lists in readme

---

Gemfile
Gemfile.lock

Use last release instead (which includes Henne's PR) instead of pointing to Henne's branch.

Update to devise_ichain_authenticatable 0.3.2

---

app/views/about/index.html.haml

Use some generic logo instead.

drop old inro video

---

Dockerfile

Update container to 15.1

---

app/controllers/projects_controller.rb
app/controllers/updates_controller.rb
app/controllers/users_controller.rb
app/models/ability.rb
app/models/user.rb
app/views/projects/_activity.html.haml
app/views/projects/membership_list.js.erb
app/views/projects/show.html.haml
app/views/updates/_activity.html.haml
app/views/updates/_more.html.haml
app/views/updates/_show_all_modal.html.haml
app/views/updates/index.js.erb
app/views/users/show.html.haml
config/routes.rb

We are at hackweek 19, most people have done a shitload of things by now...

Paginate the user history modal

---

app/views/projects/_index.html.haml
app/views/projects/_tabs.html.haml
app/views/projects/show.html.haml

More friendly language

---

app/views/devise/ichain_sessions/new.js.erb
app/views/devise/ichain_sessions/new_test.js.erb

Notify people of 401s during ajax calls

---

app/controllers/markdown_controller.rb
app/helpers/application_helper.rb

If this is part of a string like hello:wave:world it shouldnt...

Only translate lone emojis

---

Gemfile
Gemfile.lock
bin/rails
bin/rake
config/boot.rb

This is such a small app, the few milliseconds we shave off with spring are
not worth the added complexity. bootsnap was in the bundle, but never used...

Drop spring/bootsnap

---

app/views/layouts/application.html.haml
app/views/projects/show.html.haml

Add more opengraph tags for projects

---

app/controllers/projects_controller.rb
app/models/project.rb
app/views/comments/_help.html.haml
app/views/projects/_form.html.haml
config/new_project_template.md
spec/features/project_management_spec.rb

This is the second try, which doesn't break the project update page.

use project description template markdown for new projects

---

README.md

Just small things I've noticed while going through the README. See description of commits for details.

Minor improvements for the README

---

Dockerfile

Comes in handy when working with the DB...

Add mariadb-client to dev-env

---

app/controllers/projects_controller.rb
app/models/episode_project_association.rb
app/models/episodes_projects.rb
app/models/keyword.rb
app/models/membership.rb
app/models/project.rb
app/models/project_interest.rb
app/models/user.rb
app/models/user_interest.rb
db/migrate/20210312230516_rename_project_interest.rb
db/migrate/20210312232604_rename_user_interest.rb
db/migrate/20210312233011_rename_memberships.rb
db/schema.rb
spec/controllers/projects_controller_spec.rb
spec/models/project_spec.rb

We never do anything with the relationships directly.

Turn some of the relationships to HABTM

---

app/controllers/application_controller.rb
app/controllers/projects_controller.rb
spec/controllers/projects_controller_spec.rb

This is already happening in ApplicationController#set_episode

Stop loading episode twice

---

app/models/membership.rb
app/models/project.rb
app/models/user.rb
db/migrate/20210314175543_rename_memberships_back.rb
db/schema.rb

We do use the counter cache in Project.populated.
Don't drink and merge kids!

Bring back membership HABTM

---

db/schema.rb

No idea where this comes from...

Drop crono_jobs table

---

app/models/episode.rb

We don't use it anywhere but maybe in the future... :rocket:

Fix episode / project HABTM

---

db/migrate/20130408082936_create_projects.rb
db/migrate/20130408132732_create_users.rb
db/migrate/20130408142933_relate_project_to_user.rb
db/migrate/20130409093521_create_updates.rb
db/migrate/20130409110644_create_memberships.rb
db/migrate/20130410175713_create_comments.rb
db/migrate/20130411152323_create_likes.rb
db/migrate/20130412090255_create_keywords.rb
db/migrate/20130412090618_create_project_interests.rb
db/migrate/20130412091534_create_user_interests.rb
db/migrate/20130906125641_add_project_counter_cache.rb
db/migrate/20130912160959_add_devise_to_users.rb
db/migrate/20130919165239_add_aasm_state.rb
db/migrate/20131010095502_create_announcements.rb
db/migrate/20131010100037_create_enrollments.rb
db/migrate/20131011111909_create_roles.rb
db/migrate/20131011112148_user_belong_to_roles.rb
db/migrate/20131011123003_create_events.rb
db/migrate/20131011123206_project_belong_to_events.rb
db/migrate/20140829132526_add_active_to_events.rb
db/migrate/20140829151952_rename_events_to_episode.rb
db/migrate/20140903092848_rename_episode_start_end.rb
db/migrate/20140910105916_add_avatar_columns_to_projects.rb
db/migrate/20150319172246_model_for_episodes_projects_association.rb
db/migrate/20170221144704_add_url_to_projects.rb
db/migrate/20180305183055_add_location_to_user.rb
db/migrate/20180619192048_create_project_follows.rb
db/schema.rb

The `schema.db` change is the result of running `rake db:drop db:create db:migrate`

Specify the Rails release the migration was written for

---

app/assets/stylesheets/hackweek.scss

Make sure notifications fit onto the screen

---

Gemfile.lock

Revert "Update thinking-sphinx: 5.2.0 → 5.2.1 (patch)"

---

.irbrc
Dockerfile
Procfile

Without this, the leap 15.3 container had a weird mix of ruby2 and ruby3
related and never really started up.

Set image PATH correctly

---

app/controllers/comments_controller.rb
app/controllers/projects_controller.rb

Makes no sense to do this in a before_action as the object
isn't assigned attributes before the action...

Fix spam detection

---

config/routes.rb

Our IDP allows this.
Fixes #1046

Allow dots in user names

---

app/views/layouts/_header.html.haml
config/routes.rb

Drop non-resourceful user routes

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.css
app/assets/stylesheets/syntax.scss.erb
lib/haml/filters/markdown.rb

Introduces markdown syntax highlights and autolink

---

app/controllers/projects/project_follows_controller.rb

Paginate Project Followers

---

app/assets/stylesheets/hackweek.scss

Make emojis smaller

---

app/assets/javascripts/application.js

Make the table filter javascript work again

---

app/views/about/show.html.haml

Fix Haml syntax error on about page

---

app/controllers/comments_controller.rb
app/models/ability.rb
app/views/comments/index.html.haml
config/routes.rb
spec/models/ability_spec.rb

Paginated view of all comments with the ability to delete them.

Admin comment index

---

app/views/projects/index.js.erb

Scroll up when using the pager

---

app/controllers/search_controller.rb

Do not crash when there is no query param on the search

---

app/controllers/announcements_controller.rb

Fix no fallback route when enrolling on announcements

---

Dockerfile
Gemfile.lock

To get updates to the base OS etc. automatically
https://build.opensuse.org/package/show/openSUSE:infrastructure:dale/hackweek-base

Move image building to OBS

---

app/helpers/markdown_helper.rb
app/views/about/index.html.haml
app/views/projects/_list_item.html.haml
app/views/projects/_similar_projects.html.haml
app/views/projects/_tile.html.haml

Also: fold mdpreview into enrich_markdown

Sanitize markdown output

---

spec/features/comment_spec.rb

Instead test that the right things appear on the page...

Drop ".to change" from comment feature spec
